### PR TITLE
Fix inverted post rotation

### PR DESCRIPTION
**Pull request by SpexGuy**
When calculating node transforms, the post rotation wasn't inverted before.  This probably wasn't noticed because most nodes don't have a post rotation.

### CODE REVIEW

**Comment by nem0** [comment]
Thank you. Merged. 

Note: I suspect we should not use constant rotation order (XYZ) for pre- and post-rotation. I will investigate that further.

**Comment by SpexGuy** [comment]
Yeah, I couldn't find any documentation on that, but using the node's rotation order produced different results than my reference output from the official SDK.

**Comment by SpexGuy** [comment]
http://help.autodesk.com/view/FBX/2017/ENU/?guid=__files_GUID_10CDD63C_79C1_4F2D_BB28_AD2BE65A02ED_htm
has as a note that local rotation takes into account the node's rotation order, but it doesn't say anything about pre- or post-rotation.

**Comment by nem0** [comment]
They seem to do it in assimp https://github.com/assimp/assimp/blob/ce9c8a4efca102a490f288d7c37c0142d6c3a150/code/FBXConverter.cpp#L971 although assimp has a lot of issues with fbx, so it might be incorrect

**Comment by nem0** [comment]
I checked Blender, same as assimp.

**Pull request merged**
